"use client";

import { useMemo, useState } from "react";
import { BarChart3, Loader2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useReportingDashboardReport } from "@/hooks/dashboard/use-reporting-dashboard";

const navy = "bg-primary text-primary-foreground";
const border = "border border-slate-900/80";
const percent = (value: number) => `${Number(value || 0).toFixed(0)}%`;
const label = (option: any) => option?.label ?? option?.name ?? String(option ?? "");
const value = (option: any) => option?.value ?? option?.id ?? "";

function DashboardSelect({ value: selectedValue, onChange, options, placeholder, disabled = false }: any) {
  return (
    <select value={selectedValue ?? ""} onChange={(event) => onChange(event.target.value)} disabled={disabled} className="h-9 w-full rounded-md border bg-background px-2 text-sm disabled:cursor-not-allowed disabled:opacity-60">
      <option value="">{placeholder}</option>
      {options.map((option: any) => <option key={String(value(option))} value={String(value(option))}>{label(option)}</option>)}
    </select>
  );
}

function ExcelFilters({ data, filters, setFilters, mode }: any) {
  const isSubcityLevel = filters.administrative_level === "subcity";
  const isWoredaLevel = filters.administrative_level === "woreda";
  const hasWindow = Boolean(filters.window_id);
  return (
    <div className="overflow-x-auto">
      <table className="w-full min-w-[920px] border-collapse text-sm">
        <tbody>
          <tr>{["Center","Sub City","Woreda","Time","Window","Service","Officer"].map((h) => <td key={h} className={`${navy} ${border} px-2 py-2 text-center font-bold`}>{h}</td>)}</tr>
          <tr>
            <td className={`${border} px-1 py-1`}><DashboardSelect value={filters.administrative_level} onChange={(administrative_level: string) => setFilters((c: any) => ({ ...c, administrative_level, subcity_id: "", woreda_id: "", window_id: "", service_id: "", officer_id: "" }))} options={data.filters.levels ?? []} placeholder="All" /></td>
            <td className={`${border} px-1 py-1`}><DashboardSelect value={filters.subcity_id} onChange={(subcity_id: string) => setFilters((c: any) => ({ ...c, subcity_id, woreda_id: "", window_id: "", service_id: "", officer_id: "" }))} options={data.filters.subcities ?? []} placeholder={isSubcityLevel || isWoredaLevel ? "All Subcity" : "Select subcity level"} disabled={!isSubcityLevel && !isWoredaLevel} /></td>
            <td className={`${border} px-1 py-1`}><DashboardSelect value={filters.woreda_id} onChange={(woreda_id: string) => setFilters((c: any) => ({ ...c, woreda_id, window_id: "", service_id: "", officer_id: "" }))} options={data.filters.woredas ?? []} placeholder={isWoredaLevel || filters.subcity_id ? "All Woreda" : "Select woreda level/subcity"} disabled={!isWoredaLevel && !filters.subcity_id} /></td>
            <td className={`${border} px-1 py-1`}><DashboardSelect value={filters.time} onChange={(time: string) => setFilters((c: any) => ({ ...c, time }))} options={(data.filters.times ?? []).filter((item: any) => value(item) !== "")} placeholder={mode === "feedback" ? "To Date" : "All"} /></td>
            <td className={`${border} px-1 py-1`}><DashboardSelect value={filters.window_id} onChange={(window_id: string) => setFilters((c: any) => ({ ...c, window_id, service_id: "", officer_id: "" }))} options={data.filters.windows ?? []} placeholder="All Window" /></td>
            <td className={`${border} px-1 py-1`}><DashboardSelect value={filters.service_id} onChange={(service_id: string) => setFilters((c: any) => ({ ...c, service_id, officer_id: "" }))} options={data.filters.services ?? []} placeholder={hasWindow ? "All Service" : "Select window first"} disabled={!hasWindow} /></td>
            <td className={`${border} px-1 py-1`}><DashboardSelect value={filters.officer_id} onChange={(officer_id: string) => setFilters((c: any) => ({ ...c, officer_id }))} options={data.filters.officers ?? []} placeholder={hasWindow ? "All Officer" : "Select window first"} disabled={!hasWindow} /></td>
          </tr>
          {filters.time === "custom" ? <tr><td className="py-2 text-center" colSpan={7}><div className="flex justify-center gap-2"><input type="date" value={filters.from_date} onChange={(e) => setFilters((c: any) => ({ ...c, from_date: e.target.value }))} className="h-9 rounded-md border bg-background px-2 text-sm" /><input type="date" value={filters.to_date} onChange={(e) => setFilters((c: any) => ({ ...c, to_date: e.target.value }))} className="h-9 rounded-md border bg-background px-2 text-sm" /></div></td></tr> : <tr><td className="py-2 text-center" colSpan={7}>Custom</td></tr>}
        </tbody>
      </table>
    </div>
  );
}

function EmptyTableMessage({ colSpan }: { colSpan: number }) { return <tr><td className={`${border} px-4 py-10 text-center text-muted-foreground`} colSpan={colSpan}>Select a filter to display report data.</td></tr>; }

function ApplicationReportTable({ rows, requiresFilter }: any) {
  const totals = rows.reduce((a: any, r: any) => ({ total: a.total + Number(r.total || 0), approved_rejected: a.approved_rejected + Number(r.approved_rejected || 0), on_progress: a.on_progress + Number(r.on_progress || 0) }), { total: 0, approved_rejected: 0, on_progress: 0 });
  return <div className="overflow-x-auto"><table className="w-full min-w-[960px] border-collapse text-sm"><thead><tr><th className={`${navy} ${border} px-3 py-2 align-middle`} rowSpan={2}>Window</th><th className={`${navy} ${border} px-3 py-2 align-middle`} rowSpan={2}>Service</th><th className={`${navy} ${border} px-3 py-2 align-middle`} rowSpan={2}>Officer</th><th className={`${navy} ${border} px-3 py-1 text-center`} colSpan={4}>Service</th></tr><tr><th className={`${navy} ${border} px-3 py-2`}>Total Application</th><th className={`${navy} ${border} px-3 py-2`}>Complated</th><th className={`${navy} ${border} px-3 py-2`}>On progress</th><th className={`${navy} ${border} px-3 py-2`}>%</th></tr></thead><tbody>{requiresFilter || rows.length === 0 ? <EmptyTableMessage colSpan={7} /> : rows.map((row: any, i: number) => <tr key={`${row.window}-${row.service}-${row.officer}-${i}`}><td className={`${border} px-2 py-2`}>{row.window}</td><td className={`${border} px-2 py-2`}>{row.service}</td><td className={`${border} px-2 py-2`}>{row.officer}</td><td className={`${border} px-2 py-2 text-center`}>{row.total}</td><td className={`${border} px-2 py-2 text-center`}>{row.approved_rejected}</td><td className={`${border} px-2 py-2 text-center`}>{row.on_progress}</td><td className={`${border} px-2 py-2 text-center`}>{percent(row.percent)}</td></tr>)}{!requiresFilter && rows.length > 0 ? <tr className="font-bold"><td className={`${border} px-2 py-2 text-center`} colSpan={3}>Total</td><td className={`${border} px-2 py-2 text-center`}>{totals.total}</td><td className={`${border} px-2 py-2 text-center`}>{totals.approved_rejected}</td><td className={`${border} px-2 py-2 text-center`}>{totals.on_progress}</td><td className={`${border} px-2 py-2 text-center`}>{totals.total ? percent((totals.approved_rejected / totals.total) * 100) : "0%"}</td></tr> : null}</tbody></table></div>;
}

function FeedbackReportTable({ rows, requiresFilter }: any) {
  const totals = rows.reduce((a: any, r: any) => ({ high: a.high + Number(r.highly_satisfied || 0), satisfied: a.satisfied + Number(r.satisfied || 0), notSatisfied: a.notSatisfied + Number(r.not_satisfied || 0), total: a.total + Number(r.total || 0) }), { high: 0, satisfied: 0, notSatisfied: 0, total: 0 });
  return <div className="overflow-x-auto"><table className="w-full min-w-[1100px] border-collapse text-sm"><thead><tr><th className={`${navy} ${border} px-3 py-2 align-middle`} rowSpan={2}>City</th><th className={`${navy} ${border} px-3 py-2 align-middle`} rowSpan={2}>Subcity</th><th className={`${navy} ${border} px-3 py-2 align-middle`} rowSpan={2}>Woreda</th><th className={`${navy} ${border} px-3 py-2 align-middle`} rowSpan={2}>Window</th><th className={`${navy} ${border} px-3 py-2 align-middle`} rowSpan={2}>Service</th><th className={`${navy} ${border} px-3 py-1 text-center`} colSpan={5}>customer satisfaction scale</th></tr><tr><th className={`${navy} ${border} px-3 py-2`}>Highly Satisfied</th><th className={`${navy} ${border} px-3 py-2`}>Satisfied</th><th className={`${navy} ${border} px-3 py-2`}>Dissatisfied</th><th className={`${navy} ${border} px-3 py-2`}>Total</th><th className={`${navy} ${border} px-3 py-2`}>%</th></tr></thead><tbody>{requiresFilter || rows.length === 0 ? <EmptyTableMessage colSpan={10} /> : rows.map((row: any, i: number) => <tr key={`${row.city}-${row.subcity}-${row.woreda}-${row.window}-${row.service}-${i}`}><td className={`${border} px-2 py-2`}>{row.city}</td><td className={`${border} px-2 py-2`}>{row.subcity}</td><td className={`${border} px-2 py-2`}>{row.woreda}</td><td className={`${border} px-2 py-2`}>{row.window}</td><td className={`${border} px-2 py-2`}>{row.service}</td><td className={`${border} px-2 py-2 text-center`}>{row.highly_satisfied}</td><td className={`${border} px-2 py-2 text-center`}>{row.satisfied}</td><td className={`${border} px-2 py-2 text-center`}>{row.not_satisfied}</td><td className={`${border} px-2 py-2 text-center`}>{row.total}</td><td className={`${border} px-2 py-2 text-center`}>{percent(row.percent)}</td></tr>)}{!requiresFilter && rows.length > 0 ? <tr className="font-bold"><td className={`${border} px-2 py-2 text-center`} colSpan={5}>Total</td><td className={`${border} px-2 py-2 text-center`}>{totals.high}</td><td className={`${border} px-2 py-2 text-center`}>{totals.satisfied}</td><td className={`${border} px-2 py-2 text-center`}>{totals.notSatisfied}</td><td className={`${border} px-2 py-2 text-center`}>{totals.total}</td><td className={`${border} px-2 py-2 text-center`}>{totals.total ? percent(((totals.high + totals.satisfied) / totals.total) * 100) : "0%"}</td></tr> : null}</tbody></table></div>;
}

function FeedbackByLocationTable({ rows, requiresFilter }: any) {
  const totals = rows.reduce((a: any, r: any) => ({ high: a.high + Number(r.highly_satisfied || 0), satisfied: a.satisfied + Number(r.satisfied || 0), notSatisfied: a.notSatisfied + Number(r.not_satisfied || 0), total: a.total + Number(r.total || 0) }), { high: 0, satisfied: 0, notSatisfied: 0, total: 0 });
  return <div className="overflow-x-auto"><table className="w-full min-w-[900px] border-collapse text-sm"><thead><tr><th className={`${navy} ${border} px-3 py-2 align-middle`} rowSpan={2}>City</th><th className={`${navy} ${border} px-3 py-2 align-middle`} rowSpan={2}>Subcity</th><th className={`${navy} ${border} px-3 py-2 align-middle`} rowSpan={2}>Woreda</th><th className={`${navy} ${border} px-3 py-1 text-center`} colSpan={5}>customer satisfaction scale</th></tr><tr><th className={`${navy} ${border} px-3 py-2`}>Highly Satisfied</th><th className={`${navy} ${border} px-3 py-2`}>Satisfied</th><th className={`${navy} ${border} px-3 py-2`}>Dissatisfied</th><th className={`${navy} ${border} px-3 py-2`}>Total</th><th className={`${navy} ${border} px-3 py-2`}>%</th></tr></thead><tbody>{requiresFilter || rows.length === 0 ? <EmptyTableMessage colSpan={8} /> : rows.map((row: any, i: number) => <tr key={`${row.city}-${row.subcity}-${row.woreda}-${i}`}><td className={`${border} px-2 py-2`}>{row.city}</td><td className={`${border} px-2 py-2`}>{row.subcity}</td><td className={`${border} px-2 py-2`}>{row.woreda}</td><td className={`${border} px-2 py-2 text-center`}>{row.highly_satisfied}</td><td className={`${border} px-2 py-2 text-center`}>{row.satisfied}</td><td className={`${border} px-2 py-2 text-center`}>{row.not_satisfied}</td><td className={`${border} px-2 py-2 text-center`}>{row.total}</td><td className={`${border} px-2 py-2 text-center`}>{percent(row.percent)}</td></tr>)}{!requiresFilter && rows.length > 0 ? <tr className="font-bold"><td className={`${border} px-2 py-2 text-center`} colSpan={3}>Total</td><td className={`${border} px-2 py-2 text-center`}>{totals.high}</td><td className={`${border} px-2 py-2 text-center`}>{totals.satisfied}</td><td className={`${border} px-2 py-2 text-center`}>{totals.notSatisfied}</td><td className={`${border} px-2 py-2 text-center`}>{totals.total}</td><td className={`${border} px-2 py-2 text-center`}>{totals.total ? percent(((totals.high + totals.satisfied) / totals.total) * 100) : "0%"}</td></tr> : null}</tbody></table></div>;
}

export default function ReportsPage() {
  const [filters, setFilters] = useState<any>({ administrative_level: "", subcity_id: "", woreda_id: "", time: "", window_id: "", service_id: "", officer_id: "", from_date: "", to_date: "" });
  const params = useMemo(() => { const clean: Record<string, string> = {}; Object.entries(filters).forEach(([key, currentValue]) => { if (currentValue) clean[key] = String(currentValue); }); return clean; }, [filters]);
  const { data, isLoading, error } = useReportingDashboardReport(params);
  if (isLoading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin" /></div>;
  if (error || !data) return <div className="rounded-2xl border bg-card p-6 text-sm text-destructive">Failed to load reporting dashboard.</div>;
  return <Tabs defaultValue="report" className="space-y-6"><section className="rounded-3xl border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2"><div className="rounded-xl bg-primary/10 p-2 text-primary"><BarChart3 className="h-5 w-5" /></div><h1 className="text-2xl font-bold">Reports</h1></div><p className="mt-2 text-sm text-muted-foreground">{data.scope.label}</p></div><Badge variant="secondary">{data.scope.role}</Badge></div><TabsList className="mt-5"><TabsTrigger value="report">Service Report</TabsTrigger><TabsTrigger value="feedback">Feed Back Report</TabsTrigger></TabsList></section><TabsContent value="report"><Card><CardContent className="p-5"><div className="mb-6 text-center text-base font-bold">Service Report</div><ExcelFilters data={data} filters={filters} setFilters={setFilters} mode="report" /><div className="h-12" /><ApplicationReportTable rows={data.report ?? []} requiresFilter={data.requires_filter} /></CardContent></Card></TabsContent><TabsContent value="feedback"><Card><CardContent className="p-5"><div className="mb-3 text-center text-base font-bold">Feed Back Report</div><div className="mb-4 w-72 border text-sm"><div className="border-b px-3 py-1">Service</div><div className="px-3 py-1">Feed Back</div></div><ExcelFilters data={data} filters={filters} setFilters={setFilters} mode="feedback" /><div className="h-12" /><div className="mb-3 text-center text-sm font-semibold text-muted-foreground">By City / Subcity / Woreda</div><FeedbackByLocationTable rows={data.feedback_by_location ?? []} requiresFilter={data.requires_filter} /><div className="h-10" /><div className="mb-3 text-center text-sm font-semibold text-muted-foreground">By Window / Service (all)</div><FeedbackReportTable rows={data.feedback ?? []} requiresFilter={data.requires_filter} /></CardContent></Card></TabsContent></Tabs>;
}
